export const ON_INVENTORY_RECEIVED = "ON_INVENTORY_RECEIVED";
export const ON_SELECTION_CHANGED = "ON_SELECTION_CHANGED";
export const ON_LOGIN_SUCCESS = "ON_LOGIN_SUCCESS";
export const ON_CURRENT_ITEM_SELECTION_CHANGED = "ON_CURRENT_ITEM_SELECTION_CHANGED";
export const  VALIDATING_LOGIN_CREDENTIALS = "VALIDATING_LOGIN_CREDENTIALS";
export const USER_DETAILS_TO_REDUX = "USER_DETAILS_TO_REDUX";

